# cloudbuild.yaml
steps:
  # 1단계: Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args:
      - 'build'
      - '-t'
      - 'us-west1-docker.pkg.dev/hyperscale-ai-442809/gnaix-aiops/fe-dev:$SHORT_SHA'
      - '.'

  # 2단계: 빌드한 이미지를 Artifact Registry에 푸시
  # 이 단계는 아래 'images' 섹션에 의해 자동으로 처리됩니다.
  # 별도의 'docker push' 단계를 추가할 필요가 없습니다.

  # 3단계: Cloud Run에 새 이미지로 배포
  # 'gcr.io/google-cloud-sdk/gcloud'는 gcloud CLI 명령어를 실행할 수 있는 도구입니다.
  - name: 'gcr.io/google-cloud-sdk/gcloud'
    id: 'Deploy to Cloud Run'
    args:
      - 'run'
      - 'deploy'
      - 'gnaix-dev-aiops-fe'
      - '--image'
      - 'us-west1-docker.pkg.dev/hyperscale-ai-442809/gnaix-aiops/fe-dev:$SHORT_SHA'
      - '--region'
      - 'us-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' # 필요에 따라 '--no-allow-unauthenticated'로 변경

# 빌드가 성공적으로 끝나면 여기에 명시된 이미지를 자동으로 Artifact Registry에 푸시합니다.
images:
  - 'us-west1-docker.pkg.dev/hyperscale-ai-442809/gnaix-aiops/fe-dev:$SHORT_SHA'

# 이 파일에서 사용할 변수(Substitution Variables)를 정의합니다.
# gcloud builds submit 명령어 실행 시 값을 전달할 수 있습니다.
substitutions:
  _REGION: 'us-west1' # 서울 리전
  _REPO_NAME: 'gnaix-aiops' # Artifact Registry 저장소 이름
  _IMAGE_NAME: 'aiops-fe'
  _SERVICE_NAME: 'gnaix-dev-aiops-fe' # Cloud Run 서비스 이름

options:
  logging: CLOUD_LOGGING_ONLY
